In [ ]:
%pip install --upgrade pip
%pip install pandas scikit-learn IsolationForest

import pandas as pd
from sklearn.ensemble import IsolationForest
from pathlib import Path

In [6]:
import pandas as pd

df = pd.read_csv("dados/station_data_dataverse.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(3395, 24)
['sessionId', 'kwhTotal', 'dollars', 'created', 'ended', 'startTime', 'endTime', 'chargeTimeHrs', 'weekday', 'platform', 'distance', 'userId', 'stationId', 'locationId', 'managerVehicle', 'facilityType', 'Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun', 'reportedZip']

,sessionId,kwhTotal,dollars,created,ended,startTime,endTime,chargeTimeHrs,weekday,platform,...,managerVehicle,facilityType,Mon,Tues,Wed,Thurs,Fri,Sat,Sun,reportedZip
0,1366563,7.78,0.00,0014-11-18 15:40:26,0014-11-18 17:11:04,15,17,1.510556,Tue,android,...,0,3,0,1,0,0,0,0,0,0
1,3075723,9.74,0.00,0014-11-19 17:40:26,0014-11-19 19:51:04,17,19,2.177222,Wed,android,...,0,3,0,0,1,0,0,0,0,0
2,4228788,6.76,0.58,0014-11-21 12:05:46,0014-11-21 16:46:04,12,16,4.671667,Fri,android,...,0,3,0,0,0,0,1,0,0,0
3,3173284,6.17,0.00,0014-12-03 19:16:12,0014-12-03 21:02:18,19,21,1.768333,Wed,android,...,0,3,0,0,1,0,0,0,0,0
4,3266500,0.93,0.00,0014-12-11 20:56:11,0014-12-11 21:14:06,20,21,0.298611,Thu,android,...,0,3,0,0,0,1,0,0,0,0

In [7]:
df.shape

(1965239, 4)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1965239 entries, 0 to 1965238
Data columns (total 4 columns):
 #   Column                  Dtype
---  ------                  -----
 0   connectionTime_decimal  float64
 1   chargingDuration        float64
 2   kWhDelivered            float64
 3   dayIndicator            int64
dtypes: float64(3), int64(1)
memory usage: 60.0 MB

In [8]:
df.describe()

       connectionTime_decimal  chargingDuration  kWhDelivered  dayIndicator
count            1.965239e+06      1.965239e+06  1.965239e+06  1.965239e+06
mean             1.448631e+01      3.800781e+00  9.437424e+00  1.480029e+04
std              6.427672e+00      3.387723e+00  5.700660e+00  8.531910e+03
min              7.236954e-06      1.384907e-05  3.700269e-04  1.000000e+00
25%              1.424779e+01      1.443232e+00  4.868768e+00  7.424000e+03
50%              1.616805e+01      2.547029e+00  9.174554e+00  1.479300e+04
75%              1.804136e+01      5.436214e+00  1.356673e+01  2.219800e+04
max              2.400000e+01      3.941106e+01  6.253769e+01  2.960000e+04